#!/usr/bin/env python3
import requests
import re

print("=" * 80)
print("SUNGKYUNKWAN UNIVERSITY (SKKU) - STUDENT LIFE RESEARCH")
print("=" * 80)
print()

# Try to get information about SKKU student life
print("📚 ABOUT SKKU:")
print("- Founded: 1398 (one of oldest universities in East Asia)")
print("- Location: Seoul (Humanities & Social Sciences) and Suwon (Natural Sciences)")
print("- Rank: Top private university in Korea")
print("- Known for: Strong engineering, business, and Korean studies programs")
print()

print("🎓 STUDENT LIFE HIGHLIGHTS:")
print()

print("1. CAMPUS FACILITIES:")
print("   - Two campuses: Seoul (downtown) and Suwon (science/engineering)")
print("   - Modern libraries with extensive collections")
print("   - High-tech labs and research facilities")
print("   - Sports complexes and fitness centers")
print("   - Student lounges and study spaces")
print()

print("2. ACADEMIC ENVIRONMENT:")
print("   - Mix of traditional Korean and modern education")
print("   - Strong focus on research and innovation")
print("   - Many programs taught in English")
print("   - Active industry partnerships (Samsung is major supporter)")
print()

print("3. INTERNATIONAL STUDENT SUPPORT:")
print("   - Office of International Student Services (OISS)")
print("   - Buddy programs for new international students")
print("   - Korean language courses")
print("   - Cultural adaptation programs")
print("   - Housing assistance")
print()

print("4. STUDENT ACTIVITIES:")
print("   - Over 100 student clubs and organizations")
print("   - Cultural festivals and events")
print("   - Sports teams and competitions")
print("   - Volunteer and community service opportunities")
print()

print("5. HOUSING:")
print("   - On-campus dormitories available")
print("   - Off-campus housing assistance")
print("   - International student housing options")
print()

print("6. LOCATION ADVANTAGES:")
print("   SEOUL CAMPUS:")
print("   - In central Seoul (Jongno-gu)")
print("   - Near historical sites (Changdeokgung Palace)")
print("   - Excellent public transportation access")
print("   - Surrounded by cafes, restaurants, cultural sites")
print()
print("   SUWON CAMPUS:")
print("   - In Suwon (Gyeonggi-do)")
print("   - More spacious, modern facilities")
print("   - Closer to nature (mountains nearby)")
print("   - Strong engineering and science focus")
print()

print("🎯 FOR INTERNATIONAL STUDENTS LIKE YOU:")
print()

print("CHALLENGES YOU MIGHT FACE:")
print("1. Language barrier (though many courses in English)")
print("2. Cultural adjustment (Korean academic culture)")
print("3. Making friends outside international student circles")
print("4. Navigating bureaucracy (visa, housing, etc.)")
print()

print("OPPORTUNITIES YOU'LL HAVE:")
print("1. Meet students from diverse backgrounds")
print("2. Learn Korean language and culture firsthand")
print("3. Access to cutting-edge CS/ML facilities")
print("4. Networking with Korean and international companies")
print("5. Personal growth through independence")
print()

print("💡 TIPS FOR PREPARATION:")
print("1. Start learning basic Korean now (even just greetings)")
print("2. Connect with current SKKU international students online")
print("3. Research specific departments/professors in CS/ML")
print("4. Prepare for four distinct seasons (hot summers, cold winters)")
print("5. Budget for living costs (Seoul can be expensive)")
print()

print("🌐 RECOMMENDED RESOURCES:")
print("1. SKKU International Students Office website")
print("2. YouTube: Search 'SKKU vlog international student'")
print("3. Facebook groups: 'SKKU International Students'")
print("4. Instagram: Follow SKKU official accounts")
print("5. Reddit: r/korea, r/teachinginkorea for expat perspectives")
print()

print("=" * 80)
print("KEY TAKEAWAY:")
print("SKKU offers a blend of traditional Korean heritage and modern education.")
print("As an international student, you'll face challenges but also have")
print("unique opportunities for growth in one of Asia's most dynamic countries.")
print("=" * 80)